# Site settings
title: Muhammadsaid Alizada
email: ma8494@nyu.edu
description: >- # this means to ignore newlines until "baseurl:"
  A simple blog built with Jekyll.
baseurl: "" # Change if your site is in a subdirectory (e.g., "/blog")
url: "https://msaidalizada.github.io/MuhammadsaidAlizada" # Your site URL

# Author settings
author:
  name: "Muhammadsaid Alizada"
  email: "ma8494@nyu.edu"

# Navigation (if needed)
nav:
  - name: Home
    link: /
  - name: Posts
    link: /posts
  - name: About
    link: /about

# Exclusions (files and folders Jekyll should ignore)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
